# Formatting config file for Even Better TOML: https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml

[formatting]
align_entries = true
reorder_keys = false
column_width = 150
array_auto_expand = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
